'use client';
import Link from 'next/link';
import styles from './blocked.module.css';

export default function BlockedContentPolicy() {
  return (
    <div className={styles.policyContainer}>
      <div className={styles.policyContent}>
        <h1>Blocked Content Policy</h1>
        <p className={styles.date}>Date of Revision: 12/10/2024</p>

        <div className={styles.introduction}>
          <p>
            At NexusBond.AI, we are committed to providing a secure, respectful, and lawful online environment for all users. Even though users cannot upload any content on our app or website and can "only" chat and initiate the creation of AI generated content, which is accessible only to the specific user in his/her private space and is not accessible publicly, there are categories of content strictly forbidden on our APP and website and outlined as follows:
          </p>
        </div>

        <section className={styles.section}>
          <div className={styles.subsection}>
            <h3>1. Prohibited Content</h3>
            <p>
              This policy is applicable to all content, included but not limited to text, images, videos, and any other AI-generated content created on our platform.
            </p>
            <ol type="a">
              <li>
                <strong>Illegal Content:</strong> Content that contravenes local, national, or international laws and regulations is strictly prohibited. This includes, but is not limited to, content associated with illegal drugs, weapons, violence, or activities that advocate or endorse illegal actions.
              </li>
              <li>
                <strong>Hate Speech and Discrimination:</strong> We do not tolerate content that promotes hate speech, discrimination, or harassment based on various factors, including race, ethnicity, nationality, religion, gender, sexual orientation, disability, or any other protected characteristic.
              </li>
              <li>
                <strong>Violence and Harm:</strong> Content that encourages, glorifies, or promotes violence, self-harm, or harm to others is strictly prohibited. This includes content that endorses suicide, terrorism, or any form of harm.
              </li>
              <li>
                <strong>Child Exploitation:</strong> We unequivocally disallow content that exploits or poses a danger to minors, including but not limited to child pornography, sexual exploitation, or any form of harm or harassment towards minors.
              </li>
              <li>
                <strong>Content Resembling Minors:</strong> It is strictly prohibited trying to generate AI content resembling minors. We are committed to ensuring that AI-generated content on our platform does not bear any resemblance to minors or exploit their likeness. Any attempt to generate AI content resembling minors will be promptly reviewed and removed.
              </li>
              <li>
                <strong>Infringement on Privacy and Copyright:</strong> Any content that infringes upon the privacy, copyrights, trademarks, or intellectual property rights of individuals or entities is not permitted. This includes sharing personal information without consent, pirated content, or any unauthorized use of copyrighted material.
              </li>
              <li>
                <strong>Impersonation and Celebrity Content:</strong> Deceptive or harmful impersonation of real individuals, public figures, or celebrities is prohibited. This encompasses any misleading attempts to impersonate or misrepresent others.
              </li>
            </ol>
          </div>

          <div className={styles.subsection}>
            <h3>2. Content responsibility</h3>
            <p>
              You, as a user of NexusBond.AI services are solely responsible for the Output generated by the AI Companions through text messages, voice messages (currently not applicable), images, and videos. The AI Companions learn and respond based on the conversations you lead and the parameters you select. You understand and agree that NexusBond.AI does not control or endorse the content generated by the AI Companions. Therefore, you acknowledge that you are fully responsible for the Output generated by the AI and for your own actions while using the app or website.
            </p>
            <p>
              You must ensure that your interactions with the AI Companions comply with applicable laws, regulations, our Terms and Policies, in particular the Blocked Content Policy, and you shall not engage in any illegal, unethical, or harmful activities through the app or website.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>3. Content Moderation</h3>
            <p>
              While conversations between users and AI Companions are generally confidential, we have implemented a content moderation filter, to ensure compliance with our Terms and Policies, in particular with our Blocked Content Policy. In the event that the moderation filter detects any content that violates our terms, we reserve the right to manually review the flagged content and take appropriate action, which may include terminating the user's account. This measure is implemented to maintain a respectful and secure environment for all users. We strive to strike a balance between privacy and community standards, and we appreciate your understanding and cooperation in adhering to our guidelines.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>4. Content Removal and Account Suspension</h3>
            <p>
              Violations of this Blocked Content Policy may result in content removal, account suspension, or legal action as appropriate.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>5. Contact Information</h3>
            <p>
              If you have noticed any violation of these Terms from your perspective, content of any nature whatsoever or you have any questions or require further clarification regarding our Blocked Content Policy, please contact us at{' '}
              <a href="mailto:info@NexusBond.AI" className={styles.link}>info@NexusBond.AI</a> or directly report in the app and website in the <Link href="/contact" className={styles.link}>"Contact"</Link> section.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>6. Termination</h3>
            <p>
              We have the right to suspend or terminate the use of the app and website by anyone engaged in suspected infringement described above.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
