"use client";
import Link from "next/link";
import styles from "./underage.module.css";

export default function UnderagePolicy() {
  return (
    <div className={styles.policyContainer}>
      <div className={styles.policyContent}>
        <h1>Underage Policy</h1>
        <p className={styles.date}>Date of Revision: 12/10/2024</p>

        <div className={styles.introduction}>
          <p>
            At Nexusbond.AI we are committed to ensure that our platform NexusBond.AI (App and website) is used in a responsible and safe way by users who meet the legal age requirements.
          </p>
          <p>
            NexusBond.AI includes AI-generated content for adult registered users only. Therefore, users must be at least 18 years old or of legal age in their country of residence to access and engage with such content. By using NexusBond.AI app and website services users affirm that they meet the minimum age requirement and are legally permitted to access the content.
          </p>
          <p>
            We have implemented several measures to oversee and prevent the registration of users not of legal age.
          </p>
          <p>
            We are committed to ensuring that AI-generated content on our APP and website does not bear any resemblance to minors or exploit their likeness. For this purpose, we have implemented our proprietary content moderation filter to ensure full compliance with our Terms and Policies.
          </p>
        </div>

        <section className={styles.section}>
          <div className={styles.subsection}>
            <h3>1. Registering</h3>
            <p>
              When registering for the services, an initial landing page or age gate, strategically designed to restrict entry to individuals who are not of legal age is presented to the user. Prior to gaining access to the main content, users are obligated to confirm their age.
            </p>
            <p>
              Users are prompted to affirm that they are above 18, and this information is used to verify their eligibility to access the website.
            </p>
            <p>
              A transparent disclaimer emphasizes that users must be 18 years or older to access our services. Users are also notified that providing inaccurate information about their age constitutes a violation of our Terms of Service.
            </p>
            <p>
              Nexusbond.AI cannot be held responsible for any inaccuracies or misrepresentations regarding user age. It is the user"s responsibility to ensure compliance with their local laws and regulations regarding the access and consumption of the content.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>2. Content responsibility</h3>
            <p>
              You, as a user of the APP and website are solely responsible for the Output generated by the AI Companions through text messages and images. The AI Companions learn and respond based on the conversations you lead and the parameters you select. You understand and agree that Nexusbond.AI does not control or endorse the content generated by the AI Companions. Therefore, you acknowledge that you are fully responsible for the Output generated by the AI and for your own actions while using the APP.
            </p>
            <p>
              You must ensure that your interactions with the AI Companions comply with applicable laws, regulations, our Terms and Policies, in particular the <Link href="/policies/blocked-content" className={styles.link}>Blocked Content Policy</Link>, and you shall not engage in any illegal, unethical, or harmful activities through the APP or on the website.
            </p>
            <p className={styles.emphasis}>
              We explicitly point at the Blocked Content Policy prohibiting any content that exploits or poses a danger to minors, including but not limited to child pornography, sexual exploitation, or any form of harm or harassment towards minors as well as any attempt to generate AI content which would bear any resemblance to minors or exploit their likeness.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>3. Content Moderation</h3>
            <p>
              We at Nexusbond.AI value safety, respect and integrity of all our users. While conversations between users and AI Companions are generally confidential, we have implemented a content moderation filter, based on our proprietary technology to ensure compliance with our Terms and Policies, in particular with our Blocked Content Policy. In the event that the moderation filter detects any content that violates our terms, we reserve the right to manually review the flagged content and take appropriate action, which may include terminating the user"s account. This measure is implemented to maintain a respectful and secure environment for all users. We strive to strike a balance between privacy and community standards, and we appreciate your understanding and cooperation in adhering to our guidelines.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>4. Content Removal</h3>
            <p>
              Any user content that we believe, in our sole discretion, violates these provisions will be promptly removed.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>5. Contact Information</h3>
            <p>
              If you have noticed any violation of these Terms from your perspective, content of any nature whatsoever or you have any questions or require further clarification regarding our Underage Policy, please contact us at:{" "}
              <a href="mailto:info@NexusBond.ai" className={styles.link}>info@NexusBond.ai</a> or directly report in the APP or website in the <Link href="/contact" className={styles.link}>"Contact"</Link> section.
            </p>
          </div>

          <div className={styles.subsection}>
            <h3>6. Termination</h3>
            <p>
              We have the right to suspend or terminate the use of the APP and website by anyone engaged in suspected infringement described above.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
